stages:
  - test
  - build
  - deploy

test:
  image: node:9.0.0
  services:
   - mongo:3.0
  cache:
    paths:
      - node_modules/
  stage: test
  before_script:
    - npm config set proxy $PROXY
    - npm config set strict-ssl false
    - npm config set registry http://registry.npmjs.org/
    - npm install
  script:
    - npm test
    - npm run seed-dev
    - npm run integration-test

build_docker_image:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  tags:
    - docker
  before_script:
    - docker info
  script:
    - docker build --build-arg PROXY=$PROXY -t salman-activity-backend .
    - docker tag salman-activity-backend salmanactivity/salman-activity-backend
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push salmanactivity/salman-activity-backend

deploy_ifvm-docker:
  image: docker:stable
  services:
    - docker:dind
  stage: deploy
  tags:
    - docker
  before_script:
    - docker info
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - ssh-add < (echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan 167.205.35.107
  script:
    - ssh -t ppl@167.205.35.107 "docker volume inspect salman-activity-backend-storage || docker volume create salman-activity-backend-storage"
    - ssh -t ppl@167.205.35.107 "docker rm -f $(docker ps -a -q --filter=name=salman-activity-backend)"
    - ssh -t ppl@167.205.35.107 "docker run -d --env ENV=$IFVM_DOCKER_ENV --env PORT=3000 --net=host -v salman-activity-backend-storage:/storage --restart=always jauhararifin/salman-activity-backend"


