image: node:9.0.0

services:
  - mongo:3.0

cache:
  paths:
  - node_modules/

stages:
  - test

unit-test:
  stage: test
  script:
   - npm config set proxy $proxy
   - npm config set strict-ssl false
   - npm config set registry http://registry.npmjs.org/
   - npm install
   - npm test
   - npm run seed-dev
   - npm run integration-test