image: node:8.0.0

cache:
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  script:
   - npm install
   - npm run seed-dev
   - npm test
   - npm run integration-test
   - npm run seed-dev
  tags:
    - docker